version: '3'
services:
    hask-task-tracker:
        build: .
        image: hask-task-tracker
        command: hask-task-tracker
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - hask-task-tracker
