name:                hask-task-tracker
version:             0.1.0.0
github:              "githubuser/hask-task-tracker"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hask-task-tracker#readme>

dependencies:
- base # >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- hslogger
- mongoDB
- mtl
- bson
- bson-generic
- text
- time
- network
- optparse-applicative
- monad-logger
- bytestring
- data-default
- ansi-terminal
- fast-logger
- stm
- servant-auth
- servant-auth-server
- servant-swagger
- swagger2
  # - template-haskell
  # - persistent
  # - persistent-mongoDB

library:
  source-dirs: src

executables:
  hask-task-tracker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -haddock
    dependencies:
    - base
    - hask-task-tracker
    - utf8-string

tests:
  hask-task-tracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -haddock
    dependencies:
    - base
    - hask-task-tracker
